DROP DATABASE IF EXISTS TIENDAONLINE;
CREATE DATABASE TIENDAONLINE;
USE TIENDAONLINE;

DROP TABLE IF EXISTS PRODUCTOS;
CREATE TABLE PRODUCTOS(
	`id` INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    `modelo` VARCHAR(50),
    `precio` DOUBLE NOT NULL,
    `serie` VARCHAR(50),
    `genero` VARCHAR(20),
    `movimiento` VARCHAR(100),
    `modelo_maquina` VARCHAR(100),
    `detalle` VARCHAR(1500),
    `stock` INT NOT NULL
    
)ENGINE=InnoDB;

DROP TABLE IF EXISTS CAJA;
CREATE TABLE CAJA(
	id	INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    `idproducto` INT,
	`tamano_case` VARCHAR(100),
    `ancho_case` VARCHAR(100),
    `material` VARCHAR(200),
    `forma_case` VARCHAR(200),
    
    CONSTRAINT fk_caja_producto FOREIGN KEY (idproducto) REFERENCES PRODUCTOS(id)
)ENGINE=InnoDB;

DROP TABLE IF EXISTS DIAL;
CREATE TABLE DIAL(
	id	INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    `idproducto` INT,
	`tipo_dial` VARCHAR(200),
    `color_dial` VARCHAR(200),
    `cristal_dial` VARCHAR(200),
    `dial_sub` VARCHAR(200),
    `color_bisel` VARCHAR(200),
    `material_bisel` VARCHAR(200),
    
    CONSTRAINT fk_dial_producto FOREIGN KEY (idproducto) REFERENCES PRODUCTOS(id)
)ENGINE=InnoDB;

DROP TABLE IF EXISTS CORREA;
CREATE TABLE CORREA(
	id	INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    `idproducto` INT,
	`material_correa` VARCHAR(200),
    `color_correa` VARCHAR(200),
    `ancho_correa` VARCHAR(100),
    `seguro_correa` VARCHAR(200),
    
    CONSTRAINT fk_correa_producto FOREIGN KEY (idproducto) REFERENCES PRODUCTOS(id)
)ENGINE=InnoDB;

DROP TABLE IF EXISTS CARACTERISTICAS;
CREATE TABLE CARACTERISTICAS(
	id	INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    `idproducto` INT,
	`resistencia_agua` VARCHAR(200),
    `calendario` VARCHAR(200),
    `funciones` VARCHAR(250),
    `caracteristicas` VARCHAR(250),
    
    CONSTRAINT fk_caracteristicas_producto FOREIGN KEY (idproducto) REFERENCES PRODUCTOS(id)
)ENGINE=InnoDB;

DROP TABLE IF EXISTS INFO_ADICIONAL;
CREATE TABLE INFO_ADICIONAL(
	id	INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    `idproducto` INT,
	`upc_ean` VARCHAR(20),
    `incluye` VARCHAR(200),
    `garantia` VARCHAR(200),
    
    CONSTRAINT fk_infoadicinal_producto FOREIGN KEY (idproducto) REFERENCES PRODUCTOS(id)
)ENGINE=InnoDB;

DROP TABLE IF EXISTS CATEGORIAS;
CREATE TABLE CATEGORIAS(
	id	INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	name VARCHAR(100) NOT NULL UNIQUE
)ENGINE=InnoDB;

DROP TABLE IF EXISTS CATEGORIA_PRODUCTOS;
CREATE TABLE CATEGORIA_PRODUCTOS(
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	idproducto INT,
   idcategoria INT,
    
    CONSTRAINT fk_categoria_producto FOREIGN KEY (idproducto) REFERENCES PRODUCTOS(id),
    CONSTRAINT fk_categoria_categoria FOREIGN KEY (idcategoria) REFERENCES CATEGORIAS(id)
)ENGINE=InnoDB;

DROP TABLE IF EXISTS PERFIL;
CREATE TABLE PERFIL(
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    nombre VARCHAR(100) NOT NULL
)ENGINE=InnoDB;

INSERT INTO PERFIL VALUES(NULL,'Administrador');
INSERT INTO PERFIL VALUES(NULL,'Cliente');


DROP TABLE IF EXISTS USUARIOS;
CREATE TABLE USUARIOS(
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    idperfil INT,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    pass VARCHAR(100) NOT NULL,
    creation_date DATE NOT NULL,
    update_date DATE NOT NULL,
    
    CONSTRAINT fk_usuarios_perfil FOREIGN KEY (idperfil) REFERENCES PERFIL(id)
)ENGINE=InnoDB;

INSERT INTO USUARIOS VALUES(NULL,1,'ADMIN','ADMIN','admin@admin.com','$2y$10$khQh4rwU4D.7NL3RuYIKxuZFae/e.1CB3T85tQdeumYZZTlgHL7dC',CURDATE(),CURDATE());

DROP TABLE IF EXISTS SISTEMA_PAGO;
CREATE TABLE SISTEMA_PAGO(
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    nombre VARCHAR(100) NOT NULL
)ENGINE=InnoDB;

DROP TABLE IF EXISTS CIUDAD;
CREATE TABLE CIUDAD(
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    nombre VARCHAR(100) NOT NULL
)ENGINE=InnoDB;

DROP TABLE IF EXISTS ORDEN;
CREATE TABLE ORDEN(
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    idusuario INT,
    idsistema_pago INT,
    idciudad INT,
    fecha DATETIME,
    direccion_envio VARCHAR(45),
    telefono_envio VARCHAR(10),
	
    CONSTRAINT fk_orden_usuario FOREIGN KEY (idusuario) REFERENCES USUARIOS(id),
    CONSTRAINT fk_orden_sispago FOREIGN KEY (idsistema_pago) REFERENCES SISTEMA_PAGO(id),
    CONSTRAINT fk_orden_ciudad FOREIGN KEY (idciudad) REFERENCES CIUDAD(id)
)ENGINE=InnoDB;

DROP TABLE IF EXISTS ORDEN_DETALLE;
CREATE TABLE ORDEN_DETALLE(
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    idorden INT,
    idproducto INT,
    producto_nombre VARCHAR(45) NOT NULL,
    producto_precio NUMERIC NOT NULL,
    cantidad SMALLINT,
    
    CONSTRAINT fk_orden_detalle FOREIGN KEY (idorden) REFERENCES ORDEN(id),
    CONSTRAINT fk_producto_detalle FOREIGN KEY (idproducto) REFERENCES PRODUCTOS(id)
)ENGINE=InnoDB;











